### PR TITLE
Added a potential command line running capability

### PR DESCRIPTION
**Pull request by blen-desta**
Got the idea from Mike. We can use this cli library to parse arguments passed in and uses defaults if arguments aren't provided. Not sure if this is the ideal place to put it. Just wanted to put it out here to discuss.

### CODE REVIEW

**Comment by coyotesqrl** [comment]
If I'm going to use a cli parser, I always opt for https://github.com/spullara/cli-parser

😉

**Comment by coyotesqrl** [comment]
Parser preference aside, I am definitely in favor of the change.

**Comment by blen-desta** [comment]
I found this parser from https://github.com/KotlinBy/awesome-kotlin. Mike linked me https://github.com/Kotlin/kotlinx.cli but I couldn't find it in maven central.

**Comment by blen-desta** [comment]
We were looking at kotlin-bases libraries

**Comment by coyotesqrl** [comment]
That's reasonable. Stick with a Kotlin library.

**Comment by blen-desta** [comment]
Do you have a preference of where to put it? I just have it in `distribution/src/main/kotlin`

**Comment by coyotesqrl** [comment]
That seems very reasonable.

**Comment by blen-desta** [comment]
Okay I'm gonna merge it and we can keep improving it

**Pull request merged**
